# PHASE 2: Data Collection

## Objectives

In this phase, the Walmart Sales dataset is imported into the project.

The aim is to:

- Load the raw dataset.
- Verify that it exists.
- Inspect its struture.
- Preserve the original data without making any modifications.

The raw datset will always remain unchanged throughout the project.

In [8]:
import sys
import pandas as pd

print("Python path:", sys.executable)
print("Pandas version:", pd.__version__)
print("Kernel is working correctly.")

Python path: c:\Users\Udoch\walmart-sales-regression\.venv\Scripts\python.exe
Pandas version: 3.0.3
Kernel is working correctly.

In [9]:
from pathlib import Path

current_directory = Path.cwd()

project_root = (
    current_directory.parent
    if current_directory.name.lower() == "notebooks"
    else current_directory
)

raw_data_path = (
    project_root
    / "data"
    / "raw"
    / "Walmart.csv"
)

print("Dataset exists:", raw_data_path.exists())
print("Dataset path:", raw_data_path)

Dataset exists: True
Dataset path: c:\Users\Udoch\walmart-sales-regression\data\raw\Walmart.csv

In [10]:
df = pd.read_csv(raw_data_path)

df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106

## Environment Setup Notes

Before starting Phase 2, I encountered a few environment-related issues while setting up the project.

### Challenges Encountered
- The Jupyter notebook could not start because the wrong Python interpreter was selected.
- The notebook displayed errors such as:
  - `Kernel failed to start`
  - `No module named pandas`
- Although all required libraries had been installed, Jupyter was still using the global Python interpreter instead of the project's virtual environment (`.venv`).

### Resolution
To resolve the issue, I:

1. Created and activated a Python virtual environment (`.venv`).
2. Installed all project dependencies from `requirements.txt`.
3. Installed Jupyter and IPython kernel support.
4. Selected the project's `.venv` interpreter as the notebook kernel.
5. Restarted the Jupyter kernel.

After selecting the correct kernel, the notebook successfully recognized all installed libraries and was ready for development.

### Lesson Learned
Always verify that Jupyter is using the project's virtual environment rather than the global Python installation. This prevents package import errors and ensures a reproducible development environment.

In [11]:
# Verify that the file exists

if not raw_data_path.exists():
    raise FileNotFoundError(
        f"The Walmart dataset was not found at: {raw_data_path}"
    )

print("The Walmart dataset exists.")

The Walmart dataset exists.

In [12]:
# Check the file size

file_size_bytes = raw_data_path.stat().st_size

file_size_mb = file_size_bytes / (1024 ** 2)

print("Filename:", raw_data_path.name)
print(f"File size: {file_size_mb:.2f} MB")

Filename: Walmart.csv
File size: 0.35 MB

In [14]:
# Load only a preview first
data_preview = pd.read_csv(
    raw_data_path,
    nrows=5,
)

data_preview

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106

In [15]:
# Inspect the column names

data_preview.columns.tolist()

['Store',
 'Date',
 'Weekly_Sales',
 'Holiday_Flag',
 'Temperature',
 'Fuel_Price',
 'CPI',
 'Unemployment']

In [16]:
# Validata the expected columns

expected_columns = [
    "Store",
    "Date",
    "Weekly_Sales",
    "Holiday_Flag",
    "Temperature",
    "Fuel_Price",
    "CPI",
    "Unemployment",
]

actual_columns = data_preview.columns.tolist()

if actual_columns != expected_columns:
    raise ValueError(
        "The dataset columns do not match the expected structure.\n"
        f"Expected: {expected_columns}\n"
        f"Found: {actual_columns}"
    )

print("Dataset columns validated successfully.")

Dataset columns validated successfully.

In [17]:
# Load the complete dataset

df = pd.read_csv(raw_data_path)

print("Dataset columns validated successfully.")

Dataset columns validated successfully.

In [18]:
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106

In [19]:
# Check the dataset size

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 6435
Number of columns: 8

# Data Collection Verification

The Walmart dataset was sucessfully located in the raw-data directory and loaded into a panda DataFrame.

The file structure, size, and expected columns were verified.

No cleaning, transformation, feature engineering, or modification was performed during this phase.

The original dataset remains preserved in:
`data/raw/Walmart.csv`

## Phase Conclusion

The Walmart weekly sales dataset was successfully collected, stored, verified, and loaded.

The raw file has been preserved without modification.

The next phase is **Data Understanding**, where the complete dataset will be examined using:

- Dataset shape
- Data types
- Summary statistics
- Missing values
- Duplicate records
- Unique values
- Target-variable identification